/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Opportunities
         * @description List opportunities, newest first.
         */
        get: operations["list_opportunities_opportunities_get"];
        put?: never;
        /**
         * Create Opportunity
         * @description Create a new opportunity (starts in DRAFT).
         */
        post: operations["create_opportunity_opportunities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Opportunity
         * @description Fetch a single opportunity by id.
         */
        get: operations["get_opportunity_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Opportunity
         * @description Delete an opportunity.
         */
        delete: operations["delete_opportunity_opportunities__opportunity_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Opportunity
         * @description Partially update an opportunity.
         */
        patch: operations["update_opportunity_opportunities__opportunity_id__patch"];
        trace?: never;
    };
    "/opportunities/{opportunity_id}/interview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Interview
         * @description Fetch the latest interview session and its transcript.
         */
        get: operations["get_interview_opportunities__opportunity_id__interview_get"];
        put?: never;
        /**
         * Start Interview
         * @description Start the qualification interview for an opportunity.
         */
        post: operations["start_interview_opportunities__opportunity_id__interview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/continue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Continue Interview
         * @description Submit an answer and get the consultant's next move.
         */
        post: operations["continue_interview_opportunities__opportunity_id__continue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Context
         * @description Return the full context graph the consultant has built so far.
         */
        get: operations["get_context_opportunities__opportunity_id__context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Score
         * @description Return the latest score snapshot for an opportunity.
         */
        get: operations["get_score_opportunities__opportunity_id__score_get"];
        put?: never;
        /**
         * Create Score
         * @description Score an opportunity. Confidence reflects context completeness.
         */
        post: operations["create_score_opportunities__opportunity_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recommendation
         * @description Return the latest recommendation for an opportunity.
         */
        get: operations["get_recommendation_opportunities__opportunity_id__recommendation_get"];
        put?: never;
        /**
         * Create Recommendation
         * @description Decide from the latest score snapshot (status -> RECOMMENDED).
         */
        post: operations["create_recommendation_opportunities__opportunity_id__recommendation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report
         * @description Return the latest generated reports for an opportunity.
         */
        get: operations["get_report_opportunities__opportunity_id__report_get"];
        put?: never;
        /**
         * Generate Report
         * @description Generate the executive summary and detailed assessment (status -> REVIEW).
         */
        post: operations["generate_report_opportunities__opportunity_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/report.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Pdf
         * @description Return the latest reports rendered as a single downloadable PDF.
         */
        get: operations["get_report_pdf_opportunities__opportunity_id__report_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Versions
         * @description Return the opportunity's version history, newest first.
         */
        get: operations["list_versions_opportunities__opportunity_id__versions_get"];
        put?: never;
        /**
         * Create Version
         * @description Freeze the current assessment as a new numbered version.
         */
        post: operations["create_version_opportunities__opportunity_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/opportunities/{opportunity_id}/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description Return a single version of an opportunity.
         */
        get: operations["get_version_opportunities__opportunity_id__versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssessmentSnapshot
         * @description The decision state captured in a version, mirroring the report inputs.
         */
        AssessmentSnapshot: {
            /** Title */
            title: string;
            /** Problem Statement */
            problem_statement?: string | null;
            /** Summary */
            summary?: string | null;
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["SnapshotFact"][];
            /**
             * Assumptions
             * @default []
             */
            assumptions: string[];
            /**
             * Unknowns
             * @default []
             */
            unknowns: string[];
            /** Completeness */
            completeness?: {
                [key: string]: number;
            } | null;
            /** Score */
            score?: {
                [key: string]: number;
            } | null;
            /** Recommendation Type */
            recommendation_type?: string | null;
            /** Recommendation Rationale */
            recommendation_rationale?: string | null;
        };
        /** CompletenessRead */
        CompletenessRead: {
            /** Business Context Score */
            business_context_score: number;
            /** Process Understanding Score */
            process_understanding_score: number;
            /** Data Readiness Score */
            data_readiness_score: number;
            /** Roi Readiness Score */
            roi_readiness_score: number;
            /** Overall Score */
            overall_score: number;
        };
        /**
         * ContextGraphRead
         * @description The full context graph for an opportunity (UX left + right panels).
         */
        ContextGraphRead: {
            /** Nodes */
            nodes: components["schemas"]["NodeRead"][];
            /** Relationships */
            relationships: components["schemas"]["RelationshipRead"][];
            /** Evidence */
            evidence: components["schemas"]["EvidenceRead"][];
            /** Contradictions */
            contradictions: components["schemas"]["ContradictionRead"][];
            completeness: components["schemas"]["CompletenessRead"] | null;
        };
        /**
         * ContextNodeType
         * @enum {string}
         */
        ContextNodeType: "FACT" | "UNKNOWN" | "ASSUMPTION" | "CONSTRAINT" | "KPI" | "RISK" | "STAKEHOLDER";
        /**
         * ContextView
         * @description The live context model the consultant has built (UX right panel).
         */
        ContextView: {
            /** Context */
            context: {
                [key: string]: string;
            };
            /** Missing */
            missing: string[];
            /** Assumptions */
            assumptions: string[];
            /** Completeness */
            completeness: number;
        };
        /**
         * ContinueRequest
         * @description One user answer to the consultant's last question.
         */
        ContinueRequest: {
            /** Answer */
            answer: string;
        };
        /** ContradictionRead */
        ContradictionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Node A Id */
            node_a_id: string | null;
            /** Node B Id */
            node_b_id: string | null;
            /** Description */
            description: string | null;
            status: components["schemas"]["ContradictionStatus"];
            /** Resolution Note */
            resolution_note: string | null;
        };
        /**
         * ContradictionStatus
         * @enum {string}
         */
        ContradictionStatus: "OPEN" | "RESOLVED";
        /** EvidenceRead */
        EvidenceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["EvidenceType"];
            /** Content */
            content: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * EvidenceType
         * @enum {string}
         */
        EvidenceType: "USER_STATEMENT" | "DOCUMENT" | "METRIC" | "CALCULATION";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InterviewSessionRead
         * @description Full session view with transcript (GET).
         */
        InterviewSessionRead: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Opportunity Id
             * Format: uuid
             */
            opportunity_id: string;
            status: components["schemas"]["InterviewStatus"];
            context: components["schemas"]["ContextView"];
            /** Turns */
            turns: components["schemas"]["TurnRead"][];
        };
        /**
         * InterviewStartRequest
         * @description Kick off an interview with the user's raw idea/description.
         */
        InterviewStartRequest: {
            /** Message */
            message: string;
        };
        /**
         * InterviewStatus
         * @description Lifecycle of an interview session (Backend Schema v1, entity 3).
         * @enum {string}
         */
        InterviewStatus: "ACTIVE" | "PAUSED" | "COMPLETED";
        /**
         * InterviewTurnResponse
         * @description Returned after start/continue: the consultant's next move.
         */
        InterviewTurnResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["InterviewStatus"];
            /** Assistant Message */
            assistant_message: string;
            /** Done */
            done: boolean;
            context: components["schemas"]["ContextView"];
        };
        /** NodeRead */
        NodeRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["ContextNodeType"];
            /** Label */
            label: string;
            /** Description */
            description: string | null;
            /** Confidence */
            confidence: number;
            /** Source Id */
            source_id: string | null;
        };
        /**
         * OpportunityCreate
         * @description Payload to create an opportunity (Flow 1 - Create New Opportunity).
         */
        OpportunityCreate: {
            /** Title */
            title: string;
            /** Business Area */
            business_area?: string | null;
            /** Owner Id */
            owner_id?: string | null;
        };
        /**
         * OpportunityRead
         * @description Opportunity as returned by the API.
         */
        OpportunityRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Business Area */
            business_area: string | null;
            status: components["schemas"]["OpportunityStatus"];
            /** Current Version */
            current_version: number;
            /** Owner Id */
            owner_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * OpportunityStatus
         * @description Lifecycle state of an opportunity (Backend Schema v1, entity 1).
         * @enum {string}
         */
        OpportunityStatus: "DRAFT" | "INTERVIEW_ACTIVE" | "STRUCTURED" | "SCORING" | "RECOMMENDED" | "REVIEW";
        /**
         * OpportunityUpdate
         * @description Partial update. Every field is optional; unset fields are untouched.
         */
        OpportunityUpdate: {
            /** Title */
            title?: string | null;
            /** Business Area */
            business_area?: string | null;
            status?: components["schemas"]["OpportunityStatus"] | null;
            /** Owner Id */
            owner_id?: string | null;
        };
        /** RecommendationRead */
        RecommendationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Opportunity Id
             * Format: uuid
             */
            opportunity_id: string;
            /**
             * Score Snapshot Id
             * Format: uuid
             */
            score_snapshot_id: string;
            type: components["schemas"]["RecommendationType"];
            /** Rationale */
            rationale: string;
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * RecommendationType
         * @description Decision outcomes (Backend Schema v1, entity 10; Appflow flow 8).
         * @enum {string}
         */
        RecommendationType: "PROCEED" | "PROCEED_WITH_CONDITIONS" | "DEFER" | "DO_NOT_PURSUE";
        /**
         * RelationType
         * @enum {string}
         */
        RelationType: "SUPPORTS" | "CONTRADICTS" | "DEPENDS_ON" | "REQUIRES";
        /** RelationshipRead */
        RelationshipRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Node Id
             * Format: uuid
             */
            source_node_id: string;
            /**
             * Target Node Id
             * Format: uuid
             */
            target_node_id: string;
            relation_type: components["schemas"]["RelationType"];
        };
        /**
         * ReportBundle
         * @description Both decision-ready documents for an opportunity.
         */
        ReportBundle: {
            executive_summary: components["schemas"]["ReportDocumentRead"];
            detailed_assessment: components["schemas"]["ReportDocumentRead"];
        };
        /** ReportDocumentRead */
        ReportDocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Markdown Content */
            markdown_content: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * ScoreInput
         * @description Analyst-judged ICE-style inputs (1-10). Objective dimensions are derived
         *     from the context graph, so they are not provided here.
         */
        ScoreInput: {
            /** Impact */
            impact: number;
            /** Ease */
            ease: number;
            /** Strategic Alignment */
            strategic_alignment: number;
        };
        /** ScoreRead */
        ScoreRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Opportunity Id
             * Format: uuid
             */
            opportunity_id: string;
            /** Roi Score */
            roi_score: number;
            /** Impact Score */
            impact_score: number;
            /** Feasibility Score */
            feasibility_score: number;
            /** Risk Score */
            risk_score: number;
            /** Strategic Alignment Score */
            strategic_alignment_score: number;
            /** Time To Value Score */
            time_to_value_score: number;
            /** Final Score */
            final_score: number;
            /** Confidence */
            confidence: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SnapshotFact */
        SnapshotFact: {
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** TurnRead */
        TurnRead: {
            role: components["schemas"]["TurnRole"];
            /** Message */
            message: string;
            /** Reasoning Trace */
            reasoning_trace: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TurnRole
         * @description Author of a conversation turn (Backend Schema v1, entity 4).
         * @enum {string}
         */
        TurnRole: "USER" | "CONSULTANT";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VersionCreate
         * @description Optional label when cutting a new version.
         */
        VersionCreate: {
            /** Note */
            note?: string | null;
        };
        /** VersionRead */
        VersionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Version Number */
            version_number: number;
            /** Note */
            note: string | null;
            snapshot: components["schemas"]["AssessmentSnapshot"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_opportunities_opportunities_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_opportunity_opportunities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_opportunity_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_opportunity_opportunities__opportunity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_opportunity_opportunities__opportunity_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpportunityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_interview_opportunities__opportunity_id__interview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_interview_opportunities__opportunity_id__interview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_interview_opportunities__opportunity_id__continue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContinueRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_context_opportunities__opportunity_id__context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextGraphRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_score_opportunities__opportunity_id__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_score_opportunities__opportunity_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recommendation_opportunities__opportunity_id__recommendation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_recommendation_opportunities__opportunity_id__recommendation_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_opportunities__opportunity_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_report_opportunities__opportunity_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportBundle"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_pdf_opportunities__opportunity_id__report_pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_opportunities__opportunity_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_version_opportunities__opportunity_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["VersionCreate"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_opportunities__opportunity_id__versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
